# 应用名称、默认profile
spring:
  application:
    name: my-service
    port: 8661
  profiles:
    active: dev
  main:
    banner-mode: log

# Server
server:
  port: 8661
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 60000
    max-threads: 500
    min-spare-threads: 30
    max-queue-size: 100
    max-idle-time: 60000

