package org.jsj.dal.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jsj.dal.model.TTxData;
import org.jsj.dal.model.TTxDataExample;

public interface TTxDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    long countByExample(TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int deleteByExample(TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int insert(TTxData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int insertSelective(TTxData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    List<TTxData> selectByExample(TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    TTxData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTxData record, @Param("example") TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTxData record, @Param("example") TTxDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTxData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tx_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTxData record);
}